ZIMZIM\Bundles\OpinionBundle\Entity\TypeMeat:
    Source:
        columns:
            id: ~
            name: ~
        groupBy: ~
        filterable: ~
    Columns:
        id:
            filterable: true
            visible: true
            id: id
            title: id
            operatorsVisible: false
        name:
            filterable: true
            visible: true
            id: name
            title: form.opinion.typemeattype.name.label
            operatorsVisible: false