#!/bin/bash

php /home/webcv/boucherie/boucherie/app/console $@

for param in $@
do
    if [ $param = "cache:clear" ] || [ $param = "cache:warmup" ]
    then
        chmod -R 0770 /home/webcv/boucherie/boucherie/app/cache
        chown -R webcv:www-data /home/webcv/boucherie/boucherie/app/cache
        chmod -R 0770 /home/webcv/boucherie/boucherie/app/logs
        chown -R webcv:www-data /home/webcv/boucherie/boucherie/app/logs
        break
    fi
done
