parameters:
    my_user_provider.class: Centaure\Bundles\UserBundle\Security\Core\User\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: [@fos_user.user_manager,{google: google_id, facebook: facebook_id, twitter: twitter_id}]

    zz_user.registration.form.type:
        class: Centaure\Bundles\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: centaure_user_registration }

    zz_user.userupdate.form.type:
        class: Centaure\Bundles\UserBundle\Form\UserUpdateType
        tags:
            - { name: form.type, alias: centaure_bundles_userbundle_userupdate }