zimzim_opinion_butchery:
    pattern:  /
    defaults: { _controller: "ZIMZIMBundlesOpinionBundle:Butchery:index" }

zimzim_opinion_butchery_show:
    pattern:  /{id}/show
    defaults: { _controller: "ZIMZIMBundlesOpinionBundle:Butchery:show" }

zimzim_opinion_butchery_new:
    pattern:  /new
    defaults: { _controller: "ZIMZIMBundlesOpinionBundle:Butchery:new" }

zimzim_opinion_butchery_create:
    pattern:  /create
    defaults: { _controller: "ZIMZIMBundlesOpinionBundle:Butchery:create" }
    requirements: { _method: post }

zimzim_opinion_butchery_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ZIMZIMBundlesOpinionBundle:Butchery:edit" }

zimzim_opinion_butchery_update:
    pattern:  /{id}/update
    defaults: { _controller: "ZIMZIMBundlesOpinionBundle:Butchery:update" }
    requirements: { _method: post|put }

zimzim_opinion_butchery_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ZIMZIMBundlesOpinionBundle:Butchery:delete" }
    requirements: { _method: post|delete }

zimzim_opinion_butchery_displayname:
    pattern:  /{unik}/
    defaults: { _controller: "ZIMZIMBundlesOpinionBundle:Butchery:displayname" }
    requirements: { _method: get }

zimzim_opinion_butchery_showopinion:
    pattern:  /{unik}/showopinion
    defaults: { _controller: "ZIMZIMBundlesOpinionBundle:Butchery:showopinion" }
    requirements: { _method: get }

zimzim_opinion_butchery_showsales:
    pattern:  /{unik}/showsales
    defaults: { _controller: "ZIMZIMBundlesOpinionBundle:Butchery:showsales" }
    requirements: { _method: get }